const cityNames: { [key: string]: string} = {
    "Kyiv": "Київ",
    "Lviv": "Львів",
    "Odessa": "Одеса",
    "Smila": "Смiла",
    "Kharkiv": "Харків",
    "Dnipro": "Дніпро",
    "Donetsk": "Донецьк",
    "Zaporizhzhia": "Запоріжжя",
    "Luhansk": "Луганськ",
    "Poltava": "Полтава",
    "Cherkasy": "Черкаси",
    "Chernihiv": "Чернігів",
    "Sumy": "Суми",
    "Rivne": "Рівне",
    "Ivano-Frankivsk": "Івано-Франківськ",
    "Ternopil": "Тернопіль",
    "Vinnytsia": "Вінниця",
    "Uzhhorod": "Ужгород",
    "Zhytomyr": "Житомир",
    "Kherson": "Херсон",
    "Mykolaiv": "Миколаїв",
    "Sevastopol": "Севастополь",
    "Simferopol": "Сімферополь",
    "Bila Tserkva": "Біла Церква",
    "Kryvyi Rih": "Кривий Ріг",
    "Mariupol": "Маріуполь",
    "Chernivtsi": "Чернівці",
    "Melitopol": "Мелітополь",
    "Kremenchuk": "Кременчук",
    "Nikopol": "Нікополь",
    "Sloviansk": "Слов'янськ",
    "Uman": "Умань",
    "Kamianets-Podilskyi": "Кам'янець-Подільський",
    "Berdyansk": "Бердянськ",
    "Sievierodonetsk": "Сєвєродонецьк",
    "Kostiantynivka": "Костянтинівка",
    "Slavutych": "Славутич",
    "Brody": "Броди",
    "Boryspil": "Бориспіль",
    "Fastiv": "Фастів",
    "Lubny": "Лубни",
    "Mukachevo": "Мукачево",
    "Drohobych": "Дрогобич",
    "Kalush": "Калуш",
    "Shostka": "Шостка",
    "Konotop": "Конотоп",
    "Netishyn": "Нетішин",
    "Yuzhne": "Южне",
    "Nova Kakhovka": "Нова Каховка",
    "Vyshneve": "Вишневе",
    "Irpin": "Ірпінь",
    "Bucha": "Буча",
    "Vasylkiv": "Васильків",
    "Pereiaslav": "Переяслав",
    "Obukhiv": "Обухів",
    "Chortkiv": "Чортків",
    "Zhovkva": "Жовква",
    "Yavoriv": "Яворів",
    "Sambir": "Самбір",
    "Truskavets": "Трускавець",
    "Boryslav": "Борислав",
    "Novovolynsk": "Нововолинськ",
    "Kovel": "Ковель",
    "Sarny": "Сарни",
    "Dubno": "Дубно",
    "Ostroh": "Острог",
    "Izmail": "Ізмаїл",
    "Chornomorsk": "Чорноморськ",
    "Artemivsk": "Артемівськ",
    "Enerhodar": "Енергодар",
    "Bilhorod-Dknistrovskyi": "Білгород-Дністровський",
    "Yuzhnoukrainsk": "Южноукраїнськ",
    "Volodymyr": "Володимир",
    "Chuhuiv": "Чугуїв",
    "Balakliia": "Балаклія",
    "Lozova": "Лозова",
    "Kupiansk": "Куп'янськ",
    "Izium": "Ізюм",
    "New York": "Нью-Йорк",
    "Los Angeles": "Лос-Анджелес",
    "London": "Лондон",
    "Paris": "Париж",
    "Tokyo": "Токіо",
    "Berlin": "Берлін",
    "Rome": "Рим",
    "Moscow": "Москва",
    "Madrid": "Мадрид",
    "Sydney": "Сідней",
    "Seoul": "Сеул",
    "Shanghai": "Шанхай",
    "Dubai": "Дубай",
    "Istanbul": "Стамбул",
    "Toronto": "Торонто",
    "Hong Kong": "Гонконг",
    "Rio de Janeiro": "Ріо-де-Жанейро",
    "Cape Town": "Кейптаун",
    "Mexico City": "Мехіко",
    "Buenos Aires": "Буенос-Айрес",
    "Amsterdam": "Амстердам",
    "Vienna": "Відень",
    "Cairo": "Каїр",
    "Athens": "Афіни",
    "Stockholm": "Стокгольм",
    "Lisbon": "Лісабон",
    "Mumbai": "Мумбаї",
    "Chicago": "Чикаго",
    "San Francisco": "Сан-Франциско",
    "Lagos": "Лагос",
    "Lima": "Ліма",
    "Kuala Lumpur": "Куала-Лумпур",
    "Jakarta": "Джакарта",
    "Singapore": "Сінгапур",
    "Osaka": "Осака",
    "Delhi": "Делі",
    "Tunis": "Туніс",
    "Beijing": "Пекін",
    "Helsinki": "Гельсінкі",
    "Brussels": "Брюссель",
    "Warsaw": "Варшава",
    "Tallinn": "Таллінн",
    "Prague": "Прага",
    "Budapest": "Будапешт",
    "Dublin": "Дублін",
    "Copenhagen": "Копенгаген",
    "Oslo": "Осло",
    "Bern": "Берн"
  };

  export default cityNames
  